version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: users_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: users_pma
    environment:
      PMA_HOST: db
      PMA_USER: app
      PMA_PASSWORD: app
    ports:
      - "8080:80"
    depends_on:
      - db

  symfony:
    build:
      context: ./symfony
      dockerfile: Dockerfile
    container_name: users_symfony
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "mysql://app:app@db:3306/users_db?charset=utf8mb4"
    volumes:
      - ./symfony/app:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
