nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173', 'http://localhost:3000', 'http://127.0.0.1:3000']
    allow_credentials: false
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    expose_headers: []
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['*']  # en dev podés abrirlo; en prod poné dominios específicos
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
      max_age: 3600
